name: Flight Price Tracking

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  scrape-and-email:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.12

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        python -m webdriver_manager update --chrome

    - name: Run Scraper Script
      run: python flightprice-scrapping.py
      env:
        EMAIL_SENDER_ENV: ${{ secrets.EMAIL_SENDER }}
        EMAIL_PASSWORD_ENV: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_RECEIVER_ENV: ${{ secrets.EMAIL_RECEIVER }}
